"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var functions = require("firebase-functions");
var admin = require("firebase-admin");
var save_token = require("./server/save-token");
var notify = require("./server/notify");
var get_answers = require("./server/get-answers");
var add_response = require("./server/add-response");
admin.initializeApp(functions.config().firebase);
exports.saveToken = functions.https.onRequest(save_token.saveToken);
exports.notifyMorning = functions.https.onRequest(notify.notifyMorning);
exports.notifyEvening = functions.https.onRequest(notify.notifyEvening);
exports.getAnswers = functions.https.onRequest(get_answers.getAnswers);
exports.addResponse = functions.https.onRequest(add_response.addResponse);
